### ISSUE TITLE
NullPointerException (dev.20180319.221413)

### ISSUE THREAD

**Issue by SkullbocksDE** [maruohon/justenoughdimensions#24]
Hi masa,

I tried today your latest version 'justenoughdimensions-1.12.2-1.6.0-dev.20180319.221413.jar' with 'forge-1.12.1-14.22.1.2485-universal.jar' and did the following:

- /jed dimbuilder clear
- /jed dimbuilder dimtype 6 world6 _dim6 false WorldProviderSurface
- /jed dimbuilder set name Pettys World Shop
- /jed dimbuilder set-onetime generatorName default
- /jed dimbuilder set-onetime RandomSeed BedShop
- /jed dimbuilder create-as 6

The result:
`[09:16:45] [Server thread/WARN]: Couldn't process command: jed dimbuilder create-as 6
java.lang.NullPointerException: null
        at fi.dy.masa.justenoughdimensions.util.JEDJsonUtils.deepCopy(JEDJsonUtils.java:259) ~[JEDJsonUtils.class:?]
        at fi.dy.masa.justenoughdimensions.config.DimensionConfigEntry.toJson(DimensionConfigEntry.java:222) ~[DimensionConfigEntry.class:?]
        at fi.dy.masa.justenoughdimensions.config.DimensionConfig.saveConfig(DimensionConfig.java:459) ~[DimensionConfig.class:?]
        at fi.dy.masa.justenoughdimensions.config.DimensionConfig.dimbuilderSaveAs(DimensionConfig.java:725) ~[DimensionConfig.class:?]
        at fi.dy.masa.justenoughdimensions.config.DimensionConfig.dimbuilderCreateAs(DimensionConfig.java:730) ~[DimensionConfig.class:?]
        at fi.dy.masa.justenoughdimensions.command.CommandJED.dimBuilder(CommandJED.java:611) ~[CommandJED.class:?]
        at fi.dy.masa.justenoughdimensions.command.CommandJED.func_184881_a(CommandJED.java:248) ~[CommandJED.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:950) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:929) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]`

**Comment by maruohon** [comment]
I uploaded a new build `justenoughdimensions-1.12.2-1.6.0-dev.20180408.124414.jar` which fixes this crash.
